In [61]:
import numpy as np
import pandas as pd
from bokeh.plotting import figure, output_file, show
from datetime import datetime
import urllib.request as request
import json 
from operator import truediv 
from bokeh.models import ColumnDataSource
from bokeh.models.tools import HoverTool
from datetime import date

output_file('us_covid-19_positivityrate.html')

In [62]:
data=pd.read_json('https://covidtracking.com/api/v1/us/daily.json')
df=pd.DataFrame(data)

In [63]:
print(df)

         date  states  positive  negative  pending  hospitalizedCurrently  \
0    20200703      56   2786059  31427438   2237.0                37750.0
1    20200702      56   2728497  30763946   2208.0                37473.0
2    20200701      56   2674813  30152546   2604.0                36360.0
3    20200630      56   2621831  29584414   2432.0                35231.0
4    20200629      56   2577473  28979934   2194.0                33567.0
..        ...     ...       ...       ...      ...                    ...
159  20200126       1         2         0      NaN                    NaN
160  20200125       1         2         0      NaN                    NaN
161  20200124       1         2         0      NaN                    NaN
162  20200123       1         2         0      NaN                    NaN
163  20200122       1         2         0      NaN                    NaN

     hospitalizedCumulative  inIcuCurrently  inIcuCumulative  \
0                  247284.0          5589.0          10936.0
1                  245722.0          5624.0          10816.0
2                  243846.0          5509.0          10752.0
3                  242408.0          5421.0          10669.0
4                  240826.0          5378.0          10542.0
..                      ...             ...              ...
159                     NaN             NaN              NaN
160                     NaN             NaN              NaN
161                     NaN             NaN              NaN
162                     NaN             NaN              NaN
163                     NaN             NaN              NaN

     onVentilatorCurrently  ...          lastModified     total  \
0                   2049.0  ...  2020-07-03T00:00:00Z  34215734
1                   2105.0  ...  2020-07-02T00:00:00Z  33494651
2                   2098.0  ...  2020-07-01T00:00:00Z  32829963
3                   2044.0  ...  2020-06-30T00:00:00Z  32208677
4                   2011.0  ...  2020-06-29T00:00:00Z  31559601
..                     ...  ...                   ...       ...
159                    NaN  ...  2020-01-26T00:00:00Z         2
160                    NaN  ...  2020-01-25T00:00:00Z         2
161                    NaN  ...  2020-01-24T00:00:00Z         2
162                    NaN  ...  2020-01-23T00:00:00Z         2
163                    NaN  ...  2020-01-22T00:00:00Z         2

    totalTestResults    posNeg  deathIncrease hospitalizedIncrease  \
0           34213497  34213497            635                 1562
1           33492443  33492443            670                 1876
2           32827359  32827359            701                 1438
3           32206245  32206245            596                 1582
4           31557407  31557407            330                  670
..               ...       ...            ...                  ...
159                2         2              0                    0
160                2         2              0                    0
161                2         2              0                    0
162                2         2              0                    0
163                2         2              0                    0

     negativeIncrease  positiveIncrease  totalTestResultsIncrease  \
0              663492             57562                    721054
1              611400             53684                    665084
2              568132             52982                    621114
3              604480             44358                    648838
4              532904             36490                    569394
..                ...               ...                       ...
159                 0                 0                         0
160                 0                 0                         0
161                 0                 0                         0
162                 0                 0                         0
163                 0                 0                         0

                                         hash
0    feabd1e5940e81315d4dd8c7f997d4dff1a777b4
1    926d949599a345bb66d55718439690522560dfed
2    6befb05965c58b3902f12beec20245037c802bba
3    922a874533f71e362aaa52c7522136e00ef03c00
4    330ca1484f02baa6b75cbabb8beb1c3a27c92ba8
..                                        ...
159  e1cf59ab48e1cf367c4a6798a508a23d9d36bd18
160  bef2a1d5f2a13491e0e0369bbd46c10cdd12973b
161  bfffe76fc0b7cf11efe8aecd3cc7b22598d77d61
162  cee36ebf3174bf1df0daa36e1e8088a157406fad
163  d538c99729d1fee626212d1878a100c1e1204a5f

[164 rows x 25 columns]

In [64]:
positive_increase=df['positiveIncrease']
positive_increase.tolist()

[57562,
 53684,
 52982,
 44358,
 36490,
 42161,
 43471,
 44373,
 39061,
 38706,
 33018,
 27080,
 27257,
 31958,
 31055,
 27512,
 23871,
 23638,
 18655,
 21240,
 25134,
 23481,
 22051,
 20764,
 17156,
 17168,
 18774,
 23038,
 23363,
 20828,
 20314,
 19996,
 20379,
 21672,
 23842,
 23485,
 22610,
 19395,
 16620,
 18728,
 20134,
 21698,
 24519,
 26559,
 21537,
 20794,
 20976,
 20286,
 24664,
 24681,
 26658,
 21218,
 22608,
 18237,
 21603,
 24734,
 27623,
 27544,
 24986,
 22427,
 22407,
 25774,
 29323,
 33080,
 29645,
 27180,
 25098,
 22045,
 27414,
 36026,
 34196,
 31786,
 28908,
 26315,
 25837,
 27405,
 27982,
 32013,
 30840,
 30269,
 25639,
 25257,
 27871,
 30615,
 34235,
 34417,
 30481,
 30624,
 28891,
 25484,
 33212,
 31896,
 28021,
 25750,
 24708,
 21927,
 19605,
 19696,
 19051,
 17648,
 12853,
 10631,
 11449,
 9251,
 6883,
 6252,
 4665,
 3170,
 3604,
 1568,
 1250,
 921,
 1028,
 674,
 529,
 440,
 366,
 267,
 220,
 142,
 152,
 187,
 101,
 82,
 88,
 24,
 40,
 27,
 29,
 31,
 26,
 16,
 13,
 11,
 13,
 10,
 9,
 15,
 7,
 7,
 3,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [65]:
test_increase=df['totalTestResultsIncrease']
test_increase.tolist()

[721054,
 665084,
 621114,
 648838,
 569394,
 586369,
 590877,
 602947,
 637587,
 512428,
 501414,
 464802,
 512178,
 566476,
 571246,
 517739,
 488751,
 467026,
 447739,
 478569,
 499828,
 594316,
 459079,
 429546,
 420463,
 403692,
 446343,
 482914,
 509466,
 462250,
 467965,
 419864,
 413248,
 399421,
 427784,
 491504,
 415315,
 310216,
 306714,
 421768,
 383233,
 391568,
 411208,
 422062,
 408729,
 401108,
 356121,
 373562,
 363606,
 359768,
 365598,
 319604,
 308692,
 382808,
 268040,
 291606,
 298876,
 302389,
 245492,
 271488,
 231805,
 236722,
 248880,
 295619,
 233887,
 239053,
 206309,
 195884,
 206638,
 277690,
 235626,
 193199,
 323601,
 152936,
 146056,
 153763,
 146234,
 159591,
 163483,
 138095,
 152185,
 133454,
 139323,
 138891,
 157502,
 169694,
 147468,
 154321,
 151525,
 119194,
 229260,
 132569,
 119025,
 108208,
 112335,
 118648,
 87547,
 106837,
 103505,
 101631,
 84263,
 68955,
 58200,
 45272,
 45270,
 36612,
 27940,
 25089,
 17253,
 17869,
 7622,
 4586,
 9174,
 5265,
 3822,
 2494,
 1757,
 856,
 792,
 776,
 618,
 1093,
 248,
 193,
 83,
 41,
 40,
 27,
 29,
 31,
 26,
 16,
 13,
 11,
 13,
 10,
 9,
 15,
 7,
 7,
 3,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 3,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [66]:
dates=df['date']
dates.tolist()

[20200703,
 20200702,
 20200701,
 20200630,
 20200629,
 20200628,
 20200627,
 20200626,
 20200625,
 20200624,
 20200623,
 20200622,
 20200621,
 20200620,
 20200619,
 20200618,
 20200617,
 20200616,
 20200615,
 20200614,
 20200613,
 20200612,
 20200611,
 20200610,
 20200609,
 20200608,
 20200607,
 20200606,
 20200605,
 20200604,
 20200603,
 20200602,
 20200601,
 20200531,
 20200530,
 20200529,
 20200528,
 20200527,
 20200526,
 20200525,
 20200524,
 20200523,
 20200522,
 20200521,
 20200520,
 20200519,
 20200518,
 20200517,
 20200516,
 20200515,
 20200514,
 20200513,
 20200512,
 20200511,
 20200510,
 20200509,
 20200508,
 20200507,
 20200506,
 20200505,
 20200504,
 20200503,
 20200502,
 20200501,
 20200430,
 20200429,
 20200428,
 20200427,
 20200426,
 20200425,
 20200424,
 20200423,
 20200422,
 20200421,
 20200420,
 20200419,
 20200418,
 20200417,
 20200416,
 20200415,
 20200414,
 20200413,
 20200412,
 20200411,
 20200410,
 20200409,
 20200408,
 20200407,
 20200406,
 20200405,
 20200404,
 20200403,
 20200402,
 20200401,
 20200331,
 20200330,
 20200329,
 20200328,
 20200327,
 20200326,
 20200325,
 20200324,
 20200323,
 20200322,
 20200321,
 20200320,
 20200319,
 20200318,
 20200317,
 20200316,
 20200315,
 20200314,
 20200313,
 20200312,
 20200311,
 20200310,
 20200309,
 20200308,
 20200307,
 20200306,
 20200305,
 20200304,
 20200303,
 20200302,
 20200301,
 20200229,
 20200228,
 20200227,
 20200226,
 20200225,
 20200224,
 20200223,
 20200222,
 20200221,
 20200220,
 20200219,
 20200218,
 20200217,
 20200216,
 20200215,
 20200214,
 20200213,
 20200212,
 20200211,
 20200210,
 20200209,
 20200208,
 20200207,
 20200206,
 20200205,
 20200204,
 20200203,
 20200202,
 20200201,
 20200131,
 20200130,
 20200129,
 20200128,
 20200127,
 20200126,
 20200125,
 20200124,
 20200123,
 20200122]

In [67]:
positive=df['positive']
positive.tolist()

h_currently=df['hospitalizedCurrently']
h_currently.tolist()

deaths=df['deathIncrease']
deaths.tolist()

[635,
 670,
 701,
 596,
 330,
 271,
 509,
 636,
 2501,
 724,
 708,
 283,
 292,
 628,
 655,
 704,
 767,
 733,
 379,
 353,
 690,
 772,
 898,
 885,
 898,
 660,
 446,
 727,
 823,
 888,
 991,
 959,
 665,
 649,
 929,
 1179,
 1226,
 1318,
 640,
 555,
 678,
 1060,
 1335,
 1388,
 1392,
 1325,
 844,
 846,
 984,
 1502,
 1871,
 1696,
 1472,
 887,
 1024,
 1432,
 1779,
 2740,
 1932,
 2445,
 1012,
 1206,
 1541,
 1753,
 2117,
 2692,
 2042,
 1237,
 1188,
 1714,
 1865,
 1764,
 2065,
 2429,
 1765,
 1733,
 1837,
 2077,
 2141,
 2486,
 2287,
 1572,
 1630,
 1982,
 2055,
 1972,
 1944,
 1956,
 1254,
 1285,
 1440,
 1259,
 1149,
 988,
 861,
 577,
 516,
 519,
 401,
 311,
 232,
 231,
 97,
 143,
 61,
 68,
 46,
 31,
 22,
 21,
 15,
 9,
 4,
 8,
 6,
 2,
 4,
 4,
 1,
 6,
 4,
 2,
 3,
 3,
 3,
 1,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [68]:
date1 = ('2020-01-29')
date2 = (str(date.today()))
date_range=pd.date_range(date1, date2).to_pydatetime().tolist()
print(date_range)

[datetime.datetime(2020, 1, 29, 0, 0), datetime.datetime(2020, 1, 30, 0, 0), datetime.datetime(2020, 1, 31, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 2, 2, 0, 0), datetime.datetime(2020, 2, 3, 0, 0), datetime.datetime(2020, 2, 4, 0, 0), datetime.datetime(2020, 2, 5, 0, 0), datetime.datetime(2020, 2, 6, 0, 0), datetime.datetime(2020, 2, 7, 0, 0), datetime.datetime(2020, 2, 8, 0, 0), datetime.datetime(2020, 2, 9, 0, 0), datetime.datetime(2020, 2, 10, 0, 0), datetime.datetime(2020, 2, 11, 0, 0), datetime.datetime(2020, 2, 12, 0, 0), datetime.datetime(2020, 2, 13, 0, 0), datetime.datetime(2020, 2, 14, 0, 0), datetime.datetime(2020, 2, 15, 0, 0), datetime.datetime(2020, 2, 16, 0, 0), datetime.datetime(2020, 2, 17, 0, 0), datetime.datetime(2020, 2, 18, 0, 0), datetime.datetime(2020, 2, 19, 0, 0), datetime.datetime(2020, 2, 20, 0, 0), datetime.datetime(2020, 2, 21, 0, 0), datetime.datetime(2020, 2, 22, 0, 0), datetime.datetime(2020, 2, 23, 0, 0), datetime.datetime(2020, 2, 24, 0, 0), datetime.datetime(2020, 2, 25, 0, 0), datetime.datetime(2020, 2, 26, 0, 0), datetime.datetime(2020, 2, 27, 0, 0), datetime.datetime(2020, 2, 28, 0, 0), datetime.datetime(2020, 2, 29, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 3, 2, 0, 0), datetime.datetime(2020, 3, 3, 0, 0), datetime.datetime(2020, 3, 4, 0, 0), datetime.datetime(2020, 3, 5, 0, 0), datetime.datetime(2020, 3, 6, 0, 0), datetime.datetime(2020, 3, 7, 0, 0), datetime.datetime(2020, 3, 8, 0, 0), datetime.datetime(2020, 3, 9, 0, 0), datetime.datetime(2020, 3, 10, 0, 0), datetime.datetime(2020, 3, 11, 0, 0), datetime.datetime(2020, 3, 12, 0, 0), datetime.datetime(2020, 3, 13, 0, 0), datetime.datetime(2020, 3, 14, 0, 0), datetime.datetime(2020, 3, 15, 0, 0), datetime.datetime(2020, 3, 16, 0, 0), datetime.datetime(2020, 3, 17, 0, 0), datetime.datetime(2020, 3, 18, 0, 0), datetime.datetime(2020, 3, 19, 0, 0), datetime.datetime(2020, 3, 20, 0, 0), datetime.datetime(2020, 3, 21, 0, 0), datetime.datetime(2020, 3, 22, 0, 0), datetime.datetime(2020, 3, 23, 0, 0), datetime.datetime(2020, 3, 24, 0, 0), datetime.datetime(2020, 3, 25, 0, 0), datetime.datetime(2020, 3, 26, 0, 0), datetime.datetime(2020, 3, 27, 0, 0), datetime.datetime(2020, 3, 28, 0, 0), datetime.datetime(2020, 3, 29, 0, 0), datetime.datetime(2020, 3, 30, 0, 0), datetime.datetime(2020, 3, 31, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 4, 2, 0, 0), datetime.datetime(2020, 4, 3, 0, 0), datetime.datetime(2020, 4, 4, 0, 0), datetime.datetime(2020, 4, 5, 0, 0), datetime.datetime(2020, 4, 6, 0, 0), datetime.datetime(2020, 4, 7, 0, 0), datetime.datetime(2020, 4, 8, 0, 0), datetime.datetime(2020, 4, 9, 0, 0), datetime.datetime(2020, 4, 10, 0, 0), datetime.datetime(2020, 4, 11, 0, 0), datetime.datetime(2020, 4, 12, 0, 0), datetime.datetime(2020, 4, 13, 0, 0), datetime.datetime(2020, 4, 14, 0, 0), datetime.datetime(2020, 4, 15, 0, 0), datetime.datetime(2020, 4, 16, 0, 0), datetime.datetime(2020, 4, 17, 0, 0), datetime.datetime(2020, 4, 18, 0, 0), datetime.datetime(2020, 4, 19, 0, 0), datetime.datetime(2020, 4, 20, 0, 0), datetime.datetime(2020, 4, 21, 0, 0), datetime.datetime(2020, 4, 22, 0, 0), datetime.datetime(2020, 4, 23, 0, 0), datetime.datetime(2020, 4, 24, 0, 0), datetime.datetime(2020, 4, 25, 0, 0), datetime.datetime(2020, 4, 26, 0, 0), datetime.datetime(2020, 4, 27, 0, 0), datetime.datetime(2020, 4, 28, 0, 0), datetime.datetime(2020, 4, 29, 0, 0), datetime.datetime(2020, 4, 30, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 5, 2, 0, 0), datetime.datetime(2020, 5, 3, 0, 0), datetime.datetime(2020, 5, 4, 0, 0), datetime.datetime(2020, 5, 5, 0, 0), datetime.datetime(2020, 5, 6, 0, 0), datetime.datetime(2020, 5, 7, 0, 0), datetime.datetime(2020, 5, 8, 0, 0), datetime.datetime(2020, 5, 9, 0, 0), datetime.datetime(2020, 5, 10, 0, 0), datetime.datetime(2020, 5, 11, 0, 0), datetime.datetime(2020, 5, 12, 0, 0), datetime.datetime(2020, 5, 13, 0, 0), datetime.datetime(2020, 5, 14, 0, 0), datetime.datetime(2020, 5, 15, 0, 0), datetime.datetime(2020, 5, 16, 0, 0), datetime.datetime(2020, 5, 17, 0, 0), datetime.datetime(2020, 5, 18, 0, 0), datetime.datetime(2020, 5, 19, 0, 0), datetime.datetime(2020, 5, 20, 0, 0), datetime.datetime(2020, 5, 21, 0, 0), datetime.datetime(2020, 5, 22, 0, 0), datetime.datetime(2020, 5, 23, 0, 0), datetime.datetime(2020, 5, 24, 0, 0), datetime.datetime(2020, 5, 25, 0, 0), datetime.datetime(2020, 5, 26, 0, 0), datetime.datetime(2020, 5, 27, 0, 0), datetime.datetime(2020, 5, 28, 0, 0), datetime.datetime(2020, 5, 29, 0, 0), datetime.datetime(2020, 5, 30, 0, 0), datetime.datetime(2020, 5, 31, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 6, 2, 0, 0), datetime.datetime(2020, 6, 3, 0, 0), datetime.datetime(2020, 6, 4, 0, 0), datetime.datetime(2020, 6, 5, 0, 0), datetime.datetime(2020, 6, 6, 0, 0), datetime.datetime(2020, 6, 7, 0, 0), datetime.datetime(2020, 6, 8, 0, 0), datetime.datetime(2020, 6, 9, 0, 0), datetime.datetime(2020, 6, 10, 0, 0), datetime.datetime(2020, 6, 11, 0, 0), datetime.datetime(2020, 6, 12, 0, 0), datetime.datetime(2020, 6, 13, 0, 0), datetime.datetime(2020, 6, 14, 0, 0), datetime.datetime(2020, 6, 15, 0, 0), datetime.datetime(2020, 6, 16, 0, 0), datetime.datetime(2020, 6, 17, 0, 0), datetime.datetime(2020, 6, 18, 0, 0), datetime.datetime(2020, 6, 19, 0, 0), datetime.datetime(2020, 6, 20, 0, 0), datetime.datetime(2020, 6, 21, 0, 0), datetime.datetime(2020, 6, 22, 0, 0), datetime.datetime(2020, 6, 23, 0, 0), datetime.datetime(2020, 6, 24, 0, 0), datetime.datetime(2020, 6, 25, 0, 0), datetime.datetime(2020, 6, 26, 0, 0), datetime.datetime(2020, 6, 27, 0, 0), datetime.datetime(2020, 6, 28, 0, 0), datetime.datetime(2020, 6, 29, 0, 0), datetime.datetime(2020, 6, 30, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 7, 2, 0, 0), datetime.datetime(2020, 7, 3, 0, 0)]

In [69]:
rate=[]
for p, t in zip(positive_increase, test_increase):
    if t==0:
        rate.append(0)
    else:
        rate.append(p/t)
print(rate)

[0.07983035944603317, 0.08071762363851784, 0.08530157104814898, 0.06836529303154254, 0.06408567705314773, 0.07190182291355784, 0.07357030312569282, 0.07359353309660717, 0.0612637961564461, 0.07553451411710524, 0.06584977683112159, 0.05826136720582097, 0.053217826614965894, 0.05641545272880051, 0.05436361917632684, 0.05313874365268987, 0.048840820786044424, 0.05061388445182923, 0.04166489852347015, 0.044382314775925726, 0.05028529814256104, 0.039509284622995175, 0.04803312719597281, 0.04833940951609374, 0.04080263899558344, 0.042527471438621525, 0.04206182241011957, 0.04770621684192217, 0.04585781975637236, 0.0450578691184424, 0.04340922932270576, 0.04762494522035707, 0.049314213256930466, 0.05425853923554345, 0.05573373478203954, 0.04778191021843159, 0.05444060532366998, 0.06252095314232664, 0.05418728848373403, 0.04440355835435595, 0.05253722930958451, 0.055413108323458506, 0.0596267582342756, 0.06292677379152826, 0.05269261540042424, 0.05184139932387287, 0.05890132848104998, 0.054304238653824534, 0.06783166394393932, 0.0686025438615997, 0.07291615380828123, 0.06638840565199434, 0.07323804957692458, 0.047640070217968275, 0.08059617967467542, 0.08481992825936366, 0.09242294463255664, 0.09108796946978892, 0.10177928404998941, 0.08260770273455917, 0.09666314359051789, 0.1088787691891755, 0.11781983285117326, 0.11190079122113261, 0.12674924215539982, 0.11369863586735995, 0.12165247274718989, 0.11254109575054624, 0.1326667892643173, 0.12973459613237784, 0.14512829653773351, 0.16452466110073033, 0.08933223321312357, 0.17206543913794006, 0.1768979021745084, 0.17822883268406572, 0.1913508486398512, 0.20059401845968758, 0.18864346751650019, 0.21918968825808322, 0.168472582711831, 0.18925622311807813, 0.20004593642112214, 0.22042464954532692, 0.21736231920864496, 0.2028180136009523, 0.20669568991238776, 0.19844350412451967, 0.19066820656657318, 0.21380270819000957, 0.14486609090116026, 0.24059923511529846, 0.2354211300147028, 0.23796761792104096, 0.21994925891307252, 0.18480716067696043, 0.22393685677407563, 0.18435560713984855, 0.18405874112361723, 0.17364780431167656, 0.15253432704745856, 0.15417301138423609, 0.19671821305841924, 0.20434264004241032, 0.15204329578087034, 0.1707636840380203, 0.1669649248389406, 0.12635019331180997, 0.2088912073262621, 0.0877497341765068, 0.1639989504067174, 0.20082860880941997, 0.11205580989753651, 0.12801519468186134, 0.13840920983778127, 0.1764234161988773, 0.2083096186681844, 0.3119158878504673, 0.2777777777777778, 0.18298969072164947, 0.2459546925566343, 0.17108874656907594, 0.40725806451612906, 0.42487046632124353, 1.0602409638554218, 0.5853658536585366, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0, 1.0, 1.0, 1.0, 0, 1.0, 1.0, 1.0, 0, 1.0, 1.0, 1.0, 1.0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0]

In [70]:
m_dates = []
for item in dates:
    m_dates.append(str(item))
print(m_dates)

['20200703', '20200702', '20200701', '20200630', '20200629', '20200628', '20200627', '20200626', '20200625', '20200624', '20200623', '20200622', '20200621', '20200620', '20200619', '20200618', '20200617', '20200616', '20200615', '20200614', '20200613', '20200612', '20200611', '20200610', '20200609', '20200608', '20200607', '20200606', '20200605', '20200604', '20200603', '20200602', '20200601', '20200531', '20200530', '20200529', '20200528', '20200527', '20200526', '20200525', '20200524', '20200523', '20200522', '20200521', '20200520', '20200519', '20200518', '20200517', '20200516', '20200515', '20200514', '20200513', '20200512', '20200511', '20200510', '20200509', '20200508', '20200507', '20200506', '20200505', '20200504', '20200503', '20200502', '20200501', '20200430', '20200429', '20200428', '20200427', '20200426', '20200425', '20200424', '20200423', '20200422', '20200421', '20200420', '20200419', '20200418', '20200417', '20200416', '20200415', '20200414', '20200413', '20200412', '20200411', '20200410', '20200409', '20200408', '20200407', '20200406', '20200405', '20200404', '20200403', '20200402', '20200401', '20200331', '20200330', '20200329', '20200328', '20200327', '20200326', '20200325', '20200324', '20200323', '20200322', '20200321', '20200320', '20200319', '20200318', '20200317', '20200316', '20200315', '20200314', '20200313', '20200312', '20200311', '20200310', '20200309', '20200308', '20200307', '20200306', '20200305', '20200304', '20200303', '20200302', '20200301', '20200229', '20200228', '20200227', '20200226', '20200225', '20200224', '20200223', '20200222', '20200221', '20200220', '20200219', '20200218', '20200217', '20200216', '20200215', '20200214', '20200213', '20200212', '20200211', '20200210', '20200209', '20200208', '20200207', '20200206', '20200205', '20200204', '20200203', '20200202', '20200201', '20200131', '20200130', '20200129', '20200128', '20200127', '20200126', '20200125', '20200124', '20200123', '20200122']

In [71]:
r_dates = []
def insertChar(mystring, position, chartoinsert ):
    longi = len(mystring)
    mystring   =  mystring[:position] + chartoinsert + mystring[position:] 
    return mystring 
    
for m in m_dates:
    r_dates.append(insertChar(m, 4, '-'))

f_dates = []
for r in r_dates:
    f_dates.append(insertChar(r, 7, '-'))

d_dates = []
for f in f_dates:
    d_dates.append(datetime.strptime(f, '%Y-%m-%d'))

In [72]:
t_deaths=df['death']
t_deaths.tolist()

t_pos=df['positive']
t_pos.tolist()

[2786059,
 2728497,
 2674813,
 2621831,
 2577473,
 2540983,
 2498822,
 2455351,
 2410978,
 2371917,
 2333211,
 2300193,
 2273113,
 2245856,
 2213898,
 2182843,
 2155331,
 2131460,
 2107822,
 2089167,
 2067927,
 2042793,
 2019312,
 1997261,
 1976497,
 1959341,
 1942173,
 1923399,
 1900361,
 1876998,
 1856170,
 1835856,
 1815860,
 1795481,
 1773809,
 1749967,
 1726482,
 1703872,
 1684477,
 1667857,
 1649129,
 1628995,
 1607297,
 1582778,
 1556219,
 1534682,
 1513888,
 1492912,
 1472626,
 1447962,
 1423281,
 1396623,
 1375405,
 1352797,
 1334560,
 1312957,
 1288223,
 1260600,
 1233056,
 1208070,
 1185643,
 1163236,
 1137462,
 1108139,
 1075059,
 1045414,
 1018234,
 993136,
 971091,
 943677,
 907651,
 873455,
 841669,
 812761,
 786446,
 760609,
 733204,
 705222,
 673209,
 642369,
 612100,
 586461,
 561204,
 533333,
 502718,
 468483,
 434066,
 403585,
 372961,
 344070,
 318586,
 285374,
 253478,
 225457,
 199707,
 174999,
 153072,
 133467,
 113771,
 94720,
 77072,
 64219,
 53588,
 42139,
 32888,
 26005,
 19753,
 15088,
 11918,
 8314,
 6746,
 5496,
 4575,
 3547,
 2873,
 2344,
 1904,
 1538,
 1271,
 1051,
 909,
 757,
 570,
 469,
 387,
 299,
 275,
 235,
 208,
 179,
 148,
 122,
 106,
 93,
 82,
 69,
 59,
 50,
 35,
 28,
 21,
 18,
 18,
 17,
 16,
 13,
 13,
 12,
 11,
 8,
 8,
 7,
 6,
 4,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [73]:
df2=pd.DataFrame({'Date':d_dates,'Rate':rate, 'Deaths':deaths, 'Tests':test_increase, 
                  'Positive':positive_increase, 'Currently_Hospitalized':h_currently, 
                  'Date_String':f_dates, 'Total_Positive':t_pos, 'Total_Deaths':t_deaths})
df2.set_index('Date_String', inplace=True)
df3 = df2[str(date.today()):'2020-03-02']
df3

,Date,Rate,Deaths,Tests,Positive,Currently_Hospitalized,Total_Positive,Total_Deaths
Date_String,,,,,,,,
2020-07-03,2020-07-03,0.079830,635,721054,57562,37750.0,2786059,122158.0
2020-07-02,2020-07-02,0.080718,670,665084,53684,37473.0,2728497,121523.0
2020-07-01,2020-07-01,0.085302,701,621114,52982,36360.0,2674813,120853.0
2020-06-30,2020-06-30,0.068365,596,648838,44358,35231.0,2621831,120152.0
2020-06-29,2020-06-29,0.064086,330,569394,36490,33567.0,2577473,119556.0
...,...,...,...,...,...,...,...,...
2020-03-06,2020-03-06,0.182990,6,776,142,NaN,1051,26.0
2020-03-05,2020-03-05,0.245955,4,618,152,NaN,909,20.0
2020-03-04,2020-03-04,0.171089,2,1093,187,NaN,757,16.0
2020-03-03,2020-03-03,0.407258,3,248,101,NaN,570,14.0
2020-03-02,2020-03-02,0.424870,3,193,82,NaN,469,11.0

In [74]:
df4=df3['Rate']

In [75]:
ra=pd.DataFrame()
ra['Average']=df4.rolling(window=7, min_periods=1).mean()
ra['Date'] = df3['Date']
ra.set_index('Date', inplace=True)
print(ra)

             Average
Date
2020-07-03  0.079830
2020-07-02  0.080274
2020-07-01  0.081950
2020-06-30  0.078554
2020-06-29  0.075660
...              ...
2020-03-06  0.203406
2020-03-05  0.220254
2020-03-04  0.224923
2020-03-03  0.257899
2020-03-02  0.288836

[124 rows x 1 columns]

In [76]:
df5=df3.copy()
r_a=ra['Average']
df5['Rolling Average']=ra
df5

,Date,Rate,Deaths,Tests,Positive,Currently_Hospitalized,Total_Positive,Total_Deaths,Rolling Average
Date_String,,,,,,,,,
2020-07-03,2020-07-03,0.079830,635,721054,57562,37750.0,2786059,122158.0,0.079830
2020-07-02,2020-07-02,0.080718,670,665084,53684,37473.0,2728497,121523.0,0.080274
2020-07-01,2020-07-01,0.085302,701,621114,52982,36360.0,2674813,120853.0,0.081950
2020-06-30,2020-06-30,0.068365,596,648838,44358,35231.0,2621831,120152.0,0.078554
2020-06-29,2020-06-29,0.064086,330,569394,36490,33567.0,2577473,119556.0,0.075660
...,...,...,...,...,...,...,...,...,...
2020-03-06,2020-03-06,0.182990,6,776,142,NaN,1051,26.0,0.203406
2020-03-05,2020-03-05,0.245955,4,618,152,NaN,909,20.0,0.220254
2020-03-04,2020-03-04,0.171089,2,1093,187,NaN,757,16.0,0.224923
2020-03-03,2020-03-03,0.407258,3,248,101,NaN,570,14.0,0.257899
2020-03-02,2020-03-02,0.424870,3,193,82,NaN,469,11.0,0.288836

In [77]:
df2.to_excel('C:\Shiven\Python\Projects\COVID-19\df2.xlsx', index = False, header=True)

In [81]:
g=figure(title="COVID-19 Positivity Rate in the United States (Shiven Patel)", x_axis_type='datetime')
g.line(x='Date', y='Rate', source=df5, line_color='navy', line_width=2.5, legend_label='Positivity Rate')
g.line(x='Date', y='Rolling Average', source=df5, line_color='red', line_width=2.5, legend_label='Positivity Rate Rolling Average')

hover = HoverTool()
hover.tooltips=[
    ('Dates', '@Date_String'),
    ('Deaths', '@Deaths'),
    ('Positive Cases', '@Positive'),
    ('Currently Hospitalized', '@Currently_Hospitalized'),
    ('Total Cases', '@Total_Positive'),
    ('Total Deaths', '@Total_Deaths')
]

g.legend.location = "top_right"
g.legend.click_policy="hide"

g.add_tools(hover)
show(g)

In [79]:
print(str(date.today()))

2020-07-03