In [1]:
import numpy as np
import pandas as pd
from bokeh.plotting import figure, output_file, show
from datetime import datetime
import urllib.request as request
import json 
from operator import truediv 
from bokeh.models import ColumnDataSource
from bokeh.models.tools import HoverTool
from datetime import date

output_file('us_covid-19_dp.html')

In [3]:
data=pd.read_json('https://covidtracking.com/api/v1/us/daily.json')
df=pd.DataFrame(data)
df

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,lastModified,total,totalTestResults,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,hash
0,20200703,56,2786059,31427438,2237.0,37750.0,247284.0,5589.0,10936.0,2049.0,...,2020-07-03T00:00:00Z,34215734,34213497,34213497,635,1562,663492,57562,721054,feabd1e5940e81315d4dd8c7f997d4dff1a777b4
1,20200702,56,2728497,30763946,2208.0,37473.0,245722.0,5624.0,10816.0,2105.0,...,2020-07-02T00:00:00Z,33494651,33492443,33492443,670,1876,611400,53684,665084,926d949599a345bb66d55718439690522560dfed
2,20200701,56,2674813,30152546,2604.0,36360.0,243846.0,5509.0,10752.0,2098.0,...,2020-07-01T00:00:00Z,32829963,32827359,32827359,701,1438,568132,52982,621114,6befb05965c58b3902f12beec20245037c802bba
3,20200630,56,2621831,29584414,2432.0,35231.0,242408.0,5421.0,10669.0,2044.0,...,2020-06-30T00:00:00Z,32208677,32206245,32206245,596,1582,604480,44358,648838,922a874533f71e362aaa52c7522136e00ef03c00
4,20200629,56,2577473,28979934,2194.0,33567.0,240826.0,5378.0,10542.0,2011.0,...,2020-06-29T00:00:00Z,31559601,31557407,31557407,330,670,532904,36490,569394,330ca1484f02baa6b75cbabb8beb1c3a27c92ba8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,20200126,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-01-26T00:00:00Z,2,2,2,0,0,0,0,0,e1cf59ab48e1cf367c4a6798a508a23d9d36bd18
160,20200125,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-01-25T00:00:00Z,2,2,2,0,0,0,0,0,bef2a1d5f2a13491e0e0369bbd46c10cdd12973b
161,20200124,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-01-24T00:00:00Z,2,2,2,0,0,0,0,0,bfffe76fc0b7cf11efe8aecd3cc7b22598d77d61
162,20200123,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-01-23T00:00:00Z,2,2,2,0,0,0,0,0,cee36ebf3174bf1df0daa36e1e8088a157406fad
163,20200122,1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2020-01-22T00:00:00Z,2,2,2,0,0,0,0,0,d538c99729d1fee626212d1878a100c1e1204a5f

In [7]:
date1 = ('2020-01-29')
date2 = (str(date.today()))
date_range=pd.date_range(date1, date2).to_pydatetime().tolist()
print(date_range)

[datetime.datetime(2020, 1, 29, 0, 0), datetime.datetime(2020, 1, 30, 0, 0), datetime.datetime(2020, 1, 31, 0, 0), datetime.datetime(2020, 2, 1, 0, 0), datetime.datetime(2020, 2, 2, 0, 0), datetime.datetime(2020, 2, 3, 0, 0), datetime.datetime(2020, 2, 4, 0, 0), datetime.datetime(2020, 2, 5, 0, 0), datetime.datetime(2020, 2, 6, 0, 0), datetime.datetime(2020, 2, 7, 0, 0), datetime.datetime(2020, 2, 8, 0, 0), datetime.datetime(2020, 2, 9, 0, 0), datetime.datetime(2020, 2, 10, 0, 0), datetime.datetime(2020, 2, 11, 0, 0), datetime.datetime(2020, 2, 12, 0, 0), datetime.datetime(2020, 2, 13, 0, 0), datetime.datetime(2020, 2, 14, 0, 0), datetime.datetime(2020, 2, 15, 0, 0), datetime.datetime(2020, 2, 16, 0, 0), datetime.datetime(2020, 2, 17, 0, 0), datetime.datetime(2020, 2, 18, 0, 0), datetime.datetime(2020, 2, 19, 0, 0), datetime.datetime(2020, 2, 20, 0, 0), datetime.datetime(2020, 2, 21, 0, 0), datetime.datetime(2020, 2, 22, 0, 0), datetime.datetime(2020, 2, 23, 0, 0), datetime.datetime(2020, 2, 24, 0, 0), datetime.datetime(2020, 2, 25, 0, 0), datetime.datetime(2020, 2, 26, 0, 0), datetime.datetime(2020, 2, 27, 0, 0), datetime.datetime(2020, 2, 28, 0, 0), datetime.datetime(2020, 2, 29, 0, 0), datetime.datetime(2020, 3, 1, 0, 0), datetime.datetime(2020, 3, 2, 0, 0), datetime.datetime(2020, 3, 3, 0, 0), datetime.datetime(2020, 3, 4, 0, 0), datetime.datetime(2020, 3, 5, 0, 0), datetime.datetime(2020, 3, 6, 0, 0), datetime.datetime(2020, 3, 7, 0, 0), datetime.datetime(2020, 3, 8, 0, 0), datetime.datetime(2020, 3, 9, 0, 0), datetime.datetime(2020, 3, 10, 0, 0), datetime.datetime(2020, 3, 11, 0, 0), datetime.datetime(2020, 3, 12, 0, 0), datetime.datetime(2020, 3, 13, 0, 0), datetime.datetime(2020, 3, 14, 0, 0), datetime.datetime(2020, 3, 15, 0, 0), datetime.datetime(2020, 3, 16, 0, 0), datetime.datetime(2020, 3, 17, 0, 0), datetime.datetime(2020, 3, 18, 0, 0), datetime.datetime(2020, 3, 19, 0, 0), datetime.datetime(2020, 3, 20, 0, 0), datetime.datetime(2020, 3, 21, 0, 0), datetime.datetime(2020, 3, 22, 0, 0), datetime.datetime(2020, 3, 23, 0, 0), datetime.datetime(2020, 3, 24, 0, 0), datetime.datetime(2020, 3, 25, 0, 0), datetime.datetime(2020, 3, 26, 0, 0), datetime.datetime(2020, 3, 27, 0, 0), datetime.datetime(2020, 3, 28, 0, 0), datetime.datetime(2020, 3, 29, 0, 0), datetime.datetime(2020, 3, 30, 0, 0), datetime.datetime(2020, 3, 31, 0, 0), datetime.datetime(2020, 4, 1, 0, 0), datetime.datetime(2020, 4, 2, 0, 0), datetime.datetime(2020, 4, 3, 0, 0), datetime.datetime(2020, 4, 4, 0, 0), datetime.datetime(2020, 4, 5, 0, 0), datetime.datetime(2020, 4, 6, 0, 0), datetime.datetime(2020, 4, 7, 0, 0), datetime.datetime(2020, 4, 8, 0, 0), datetime.datetime(2020, 4, 9, 0, 0), datetime.datetime(2020, 4, 10, 0, 0), datetime.datetime(2020, 4, 11, 0, 0), datetime.datetime(2020, 4, 12, 0, 0), datetime.datetime(2020, 4, 13, 0, 0), datetime.datetime(2020, 4, 14, 0, 0), datetime.datetime(2020, 4, 15, 0, 0), datetime.datetime(2020, 4, 16, 0, 0), datetime.datetime(2020, 4, 17, 0, 0), datetime.datetime(2020, 4, 18, 0, 0), datetime.datetime(2020, 4, 19, 0, 0), datetime.datetime(2020, 4, 20, 0, 0), datetime.datetime(2020, 4, 21, 0, 0), datetime.datetime(2020, 4, 22, 0, 0), datetime.datetime(2020, 4, 23, 0, 0), datetime.datetime(2020, 4, 24, 0, 0), datetime.datetime(2020, 4, 25, 0, 0), datetime.datetime(2020, 4, 26, 0, 0), datetime.datetime(2020, 4, 27, 0, 0), datetime.datetime(2020, 4, 28, 0, 0), datetime.datetime(2020, 4, 29, 0, 0), datetime.datetime(2020, 4, 30, 0, 0), datetime.datetime(2020, 5, 1, 0, 0), datetime.datetime(2020, 5, 2, 0, 0), datetime.datetime(2020, 5, 3, 0, 0), datetime.datetime(2020, 5, 4, 0, 0), datetime.datetime(2020, 5, 5, 0, 0), datetime.datetime(2020, 5, 6, 0, 0), datetime.datetime(2020, 5, 7, 0, 0), datetime.datetime(2020, 5, 8, 0, 0), datetime.datetime(2020, 5, 9, 0, 0), datetime.datetime(2020, 5, 10, 0, 0), datetime.datetime(2020, 5, 11, 0, 0), datetime.datetime(2020, 5, 12, 0, 0), datetime.datetime(2020, 5, 13, 0, 0), datetime.datetime(2020, 5, 14, 0, 0), datetime.datetime(2020, 5, 15, 0, 0), datetime.datetime(2020, 5, 16, 0, 0), datetime.datetime(2020, 5, 17, 0, 0), datetime.datetime(2020, 5, 18, 0, 0), datetime.datetime(2020, 5, 19, 0, 0), datetime.datetime(2020, 5, 20, 0, 0), datetime.datetime(2020, 5, 21, 0, 0), datetime.datetime(2020, 5, 22, 0, 0), datetime.datetime(2020, 5, 23, 0, 0), datetime.datetime(2020, 5, 24, 0, 0), datetime.datetime(2020, 5, 25, 0, 0), datetime.datetime(2020, 5, 26, 0, 0), datetime.datetime(2020, 5, 27, 0, 0), datetime.datetime(2020, 5, 28, 0, 0), datetime.datetime(2020, 5, 29, 0, 0), datetime.datetime(2020, 5, 30, 0, 0), datetime.datetime(2020, 5, 31, 0, 0), datetime.datetime(2020, 6, 1, 0, 0), datetime.datetime(2020, 6, 2, 0, 0), datetime.datetime(2020, 6, 3, 0, 0), datetime.datetime(2020, 6, 4, 0, 0), datetime.datetime(2020, 6, 5, 0, 0), datetime.datetime(2020, 6, 6, 0, 0), datetime.datetime(2020, 6, 7, 0, 0), datetime.datetime(2020, 6, 8, 0, 0), datetime.datetime(2020, 6, 9, 0, 0), datetime.datetime(2020, 6, 10, 0, 0), datetime.datetime(2020, 6, 11, 0, 0), datetime.datetime(2020, 6, 12, 0, 0), datetime.datetime(2020, 6, 13, 0, 0), datetime.datetime(2020, 6, 14, 0, 0), datetime.datetime(2020, 6, 15, 0, 0), datetime.datetime(2020, 6, 16, 0, 0), datetime.datetime(2020, 6, 17, 0, 0), datetime.datetime(2020, 6, 18, 0, 0), datetime.datetime(2020, 6, 19, 0, 0), datetime.datetime(2020, 6, 20, 0, 0), datetime.datetime(2020, 6, 21, 0, 0), datetime.datetime(2020, 6, 22, 0, 0), datetime.datetime(2020, 6, 23, 0, 0), datetime.datetime(2020, 6, 24, 0, 0), datetime.datetime(2020, 6, 25, 0, 0), datetime.datetime(2020, 6, 26, 0, 0), datetime.datetime(2020, 6, 27, 0, 0), datetime.datetime(2020, 6, 28, 0, 0), datetime.datetime(2020, 6, 29, 0, 0), datetime.datetime(2020, 6, 30, 0, 0), datetime.datetime(2020, 7, 1, 0, 0), datetime.datetime(2020, 7, 2, 0, 0), datetime.datetime(2020, 7, 3, 0, 0)]

In [11]:
dates=df['date']
dates.tolist()

[20200703,
 20200702,
 20200701,
 20200630,
 20200629,
 20200628,
 20200627,
 20200626,
 20200625,
 20200624,
 20200623,
 20200622,
 20200621,
 20200620,
 20200619,
 20200618,
 20200617,
 20200616,
 20200615,
 20200614,
 20200613,
 20200612,
 20200611,
 20200610,
 20200609,
 20200608,
 20200607,
 20200606,
 20200605,
 20200604,
 20200603,
 20200602,
 20200601,
 20200531,
 20200530,
 20200529,
 20200528,
 20200527,
 20200526,
 20200525,
 20200524,
 20200523,
 20200522,
 20200521,
 20200520,
 20200519,
 20200518,
 20200517,
 20200516,
 20200515,
 20200514,
 20200513,
 20200512,
 20200511,
 20200510,
 20200509,
 20200508,
 20200507,
 20200506,
 20200505,
 20200504,
 20200503,
 20200502,
 20200501,
 20200430,
 20200429,
 20200428,
 20200427,
 20200426,
 20200425,
 20200424,
 20200423,
 20200422,
 20200421,
 20200420,
 20200419,
 20200418,
 20200417,
 20200416,
 20200415,
 20200414,
 20200413,
 20200412,
 20200411,
 20200410,
 20200409,
 20200408,
 20200407,
 20200406,
 20200405,
 20200404,
 20200403,
 20200402,
 20200401,
 20200331,
 20200330,
 20200329,
 20200328,
 20200327,
 20200326,
 20200325,
 20200324,
 20200323,
 20200322,
 20200321,
 20200320,
 20200319,
 20200318,
 20200317,
 20200316,
 20200315,
 20200314,
 20200313,
 20200312,
 20200311,
 20200310,
 20200309,
 20200308,
 20200307,
 20200306,
 20200305,
 20200304,
 20200303,
 20200302,
 20200301,
 20200229,
 20200228,
 20200227,
 20200226,
 20200225,
 20200224,
 20200223,
 20200222,
 20200221,
 20200220,
 20200219,
 20200218,
 20200217,
 20200216,
 20200215,
 20200214,
 20200213,
 20200212,
 20200211,
 20200210,
 20200209,
 20200208,
 20200207,
 20200206,
 20200205,
 20200204,
 20200203,
 20200202,
 20200201,
 20200131,
 20200130,
 20200129,
 20200128,
 20200127,
 20200126,
 20200125,
 20200124,
 20200123,
 20200122]

In [12]:
df['death']

0      122158.0
1      121523.0
2      120853.0
3      120152.0
4      119556.0
         ...
159         NaN
160         NaN
161         NaN
162         NaN
163         NaN
Name: death, Length: 164, dtype: float64

In [9]:
m_dates = []
for item in dates:
    m_dates.append(str(item))
print(m_dates)

['20200703', '20200702', '20200701', '20200630', '20200629', '20200628', '20200627', '20200626', '20200625', '20200624', '20200623', '20200622', '20200621', '20200620', '20200619', '20200618', '20200617', '20200616', '20200615', '20200614', '20200613', '20200612', '20200611', '20200610', '20200609', '20200608', '20200607', '20200606', '20200605', '20200604', '20200603', '20200602', '20200601', '20200531', '20200530', '20200529', '20200528', '20200527', '20200526', '20200525', '20200524', '20200523', '20200522', '20200521', '20200520', '20200519', '20200518', '20200517', '20200516', '20200515', '20200514', '20200513', '20200512', '20200511', '20200510', '20200509', '20200508', '20200507', '20200506', '20200505', '20200504', '20200503', '20200502', '20200501', '20200430', '20200429', '20200428', '20200427', '20200426', '20200425', '20200424', '20200423', '20200422', '20200421', '20200420', '20200419', '20200418', '20200417', '20200416', '20200415', '20200414', '20200413', '20200412', '20200411', '20200410', '20200409', '20200408', '20200407', '20200406', '20200405', '20200404', '20200403', '20200402', '20200401', '20200331', '20200330', '20200329', '20200328', '20200327', '20200326', '20200325', '20200324', '20200323', '20200322', '20200321', '20200320', '20200319', '20200318', '20200317', '20200316', '20200315', '20200314', '20200313', '20200312', '20200311', '20200310', '20200309', '20200308', '20200307', '20200306', '20200305', '20200304', '20200303', '20200302', '20200301', '20200229', '20200228', '20200227', '20200226', '20200225', '20200224', '20200223', '20200222', '20200221', '20200220', '20200219', '20200218', '20200217', '20200216', '20200215', '20200214', '20200213', '20200212', '20200211', '20200210', '20200209', '20200208', '20200207', '20200206', '20200205', '20200204', '20200203', '20200202', '20200201', '20200131', '20200130', '20200129', '20200128', '20200127', '20200126', '20200125', '20200124', '20200123', '20200122']

In [10]:
r_dates = []
def insertChar(mystring, position, chartoinsert ):
    longi = len(mystring)
    mystring   =  mystring[:position] + chartoinsert + mystring[position:] 
    return mystring 
    
for m in m_dates:
    r_dates.append(insertChar(m, 4, '-'))

f_dates = []
for r in r_dates:
    f_dates.append(insertChar(r, 7, '-'))

d_dates = []
for f in f_dates:
    d_dates.append(datetime.strptime(f, '%Y-%m-%d'))

In [16]:
df2=pd.DataFrame({'Date':d_dates, 'Deaths':df['deathIncrease'].tolist(), 'Tests':df['totalTestResultsIncrease'].tolist(), 
                  'Positive':df['positiveIncrease'].tolist(), 'Currently_Hospitalized':df['hospitalizedCurrently'].tolist(), 
                  'Date_String':f_dates, 'Total_Positive':df['positive'].tolist(), 'Total_Deaths':df['death'].tolist()})
df2.set_index('Date_String', inplace=True)
df2

,Date,Deaths,Tests,Positive,Currently_Hospitalized,Total_Positive,Total_Deaths
Date_String,,,,,,,
2020-07-03,2020-07-03,635,721054,57562,37750.0,2786059,122158.0
2020-07-02,2020-07-02,670,665084,53684,37473.0,2728497,121523.0
2020-07-01,2020-07-01,701,621114,52982,36360.0,2674813,120853.0
2020-06-30,2020-06-30,596,648838,44358,35231.0,2621831,120152.0
2020-06-29,2020-06-29,330,569394,36490,33567.0,2577473,119556.0
...,...,...,...,...,...,...,...
2020-01-26,2020-01-26,0,0,0,NaN,2,NaN
2020-01-25,2020-01-25,0,0,0,NaN,2,NaN
2020-01-24,2020-01-24,0,0,0,NaN,2,NaN
2020-01-23,2020-01-23,0,0,0,NaN,2,NaN
2020-01-22,2020-01-22,0,0,0,NaN,2,NaN

In [21]:
df2['RAveragePos']=df2['Positive'].rolling(window=7, min_periods=1).mean()
df2['RAverageDeaths']=df2['Deaths'].rolling(window=7, min_periods=1).mean()
df2

,Date,Deaths,Tests,Positive,Currently_Hospitalized,Total_Positive,Total_Deaths,RAveragePos,RAverageDeaths
Date_String,,,,,,,,,
2020-07-03,2020-07-03,635,721054,57562,37750.0,2786059,122158.0,57562.000000,635.000000
2020-07-02,2020-07-02,670,665084,53684,37473.0,2728497,121523.0,55623.000000,652.500000
2020-07-01,2020-07-01,701,621114,52982,36360.0,2674813,120853.0,54742.666667,668.666667
2020-06-30,2020-06-30,596,648838,44358,35231.0,2621831,120152.0,52146.500000,650.500000
2020-06-29,2020-06-29,330,569394,36490,33567.0,2577473,119556.0,49015.200000,586.400000
...,...,...,...,...,...,...,...,...,...
2020-01-26,2020-01-26,0,0,0,NaN,2,NaN,0.285714,0.000000
2020-01-25,2020-01-25,0,0,0,NaN,2,NaN,0.142857,0.000000
2020-01-24,2020-01-24,0,0,0,NaN,2,NaN,0.142857,0.000000
2020-01-23,2020-01-23,0,0,0,NaN,2,NaN,0.142857,0.000000
2020-01-22,2020-01-22,0,0,0,NaN,2,NaN,0.000000,0.000000

In [26]:
g=figure(title="COVID-19 Daily New Cases", x_axis_type='datetime')
g.line(x='Date', y='Positive', source=df2, line_color='navy', line_width=2.5, legend_label='New Cases')
g.line(x='Date', y='RAveragePos', source=df2, line_color='blue', line_width=2.5, legend_label='New Cases Rolling Average')

hover = HoverTool()
hover.tooltips=[
    ('Dates', '@Date_String'),
    ('Deaths', '@Deaths'),
    ('Positive Cases', '@Positive'),
    ('Currently Hospitalized', '@Currently_Hospitalized'),
    ('Total Cases', '@Total_Positive'),
    ('Total Deaths', '@Total_Deaths'),
    ('Total Tests', '@Tests')
]

g.legend.location = "top_left"
g.legend.click_policy="hide"

g.add_tools(hover)
show(g)